Post.destroy_all
Comment.destroy_all

one = Post.create(title: "Post One", author: "L. Carroll", content: "The Queen smiled and passed on.\n'Who ARE you talking to?' said the King, going up to Alice, and looking at the Cat's head with great curiosity.\n'It's a friend of mine&mdash;a Cheshire Cat,' said Alice: 'allow me to  introduce it.'\n'I don't like the look of it at all,' said the King: 'however, it may  kiss my hand if it likes.'")
two = Post.create(title: "Post Two", author: "H. Melville", content: "If I say, that in any creature breathing is only a function indispensable to vitality, inasmuch as it withdraws from the air a certain element, which being subsequently brought into contact with the blood imparts to the blood its vivifying principle, I do not think I shall err; though I may possibly use some superfluous scientific words. Assume it, and it follows that if all the blood in a man could be aerated with one breath, he might then seal up his nostrils and not fetch another for a considerable time. That is to say, he would then live without breathing. Anomalous as it may seem, this is precisely the case with the whale, who systematically lives, by intervals, his full hour and more (when at the bottom) without drawing a single breath, or so much as in any way inhaling a particle of air; for, remember, he has no gills. How is this? Between his ribs and on each side of his spine he is supplied with a remarkable involved Cretan labyrinth of vermicelli-like vessels, which vessels, when he quits the surface, are completely distended with oxygenated blood. So that for an hour or more, a thousand fathoms in the sea, he carries a surplus stock of vitality in him, just as the camel crossing the waterless desert carries a surplus supply of drink for future use in its four supplementary stomachs. The anatomical fact of this labyrinth is indisputable; and that the supposition founded upon it is reasonable and true, seems the more cogent to me, when I consider the otherwise inexplicable obstinacy of that leviathan in HAVING HIS SPOUTINGS OUT, as the fishermen phrase it. This is what I mean. If unmolested, upon rising to the surface, the Sperm Whale will continue there for a period of time exactly uniform with all his other unmolested risings. Say he stays eleven minutes, and jets seventy times, that is, respires seventy breaths; then whenever he rises again, he will be sure to have his seventy breaths over again, to a minute. Now, if after he fetches a few breaths you alarm him, so that he sounds, he will be always dodging up again to make good his regular allowance of air. And not till those seventy breaths are told, will he finally go down to stay out his full term below. Remark, however, that in different individuals these rates are different; but in any one they are alike. Now, why should the whale thus insist upon having his spoutings out, unless it be to replenish his reservoir of air, ere descending for good? How obvious is it, too, that this necessity for the whale's rising exposes him to all the fatal hazards of the chase. For not by hook or by net could this vast leviathan be caught, when sailing a thousand fathoms beneath the sunlight. Not so much thy skill, then, O hunter, as the great necessities that strike the victory to thee!")
three = Post.create(title: "Post Three", author: "E.R. Burroughs", content: "He could not use his short-sword to advantage because I was too close to him, nor could he draw his pistol, which he attempted to do in direct opposition to Martian custom which says that you may not fight a fellow warrior in private combat with any other than the weapon with which you are attacked.  In fact he could do nothing but make a wild and futile attempt to dislodge me.  With all his immense bulk he was little if any stronger than I, and it was but the matter of a moment or two before he sank, bleeding and lifeless, to the floor.")

Comment.create(author: "The White Rabbit", content: "First! OBVI.", post_id: one.id)
Comment.create(author: "Ishmail", content: "Call me 'First'.", post_id: two.id)
Comment.create(author: "Tarzan", content: "Tarzan first!", post_id: three.id)
